### ISSUE TITLE
Useful System Log Queries link is broken

### ISSUE THREAD

**Issue by nicolastriballier-okta** [okta/okta.github.io#1545] opened 2017-12-08 02:17 UTC
https://developer.okta.com/docs/api/resources/system_log.html#examples > “Useful System Log Queries” link is broken

**Comment by nbarbettini** [comment] 2017-12-18 05:43
Thanks! Tracking in #1562

**Comment by nbarbettini** [comment] 2017-12-18 19:59
Turns out the link is fine, it's this extra query param that's causing it to break:

![url-gack](https://user-images.githubusercontent.com/7525482/34125321-c1037e78-e3ea-11e7-9b21-979fc5f989b7.png)

@robertjd can you link this issue to the open one you mentioned for fixing the ga params?

**Comment by jmelberg-okta** [comment] 2017-12-20 00:57
Closing due to duplicated issue #1562

**Comment by nbarbettini** [comment] 2017-12-21 00:10
@jmelberg-okta This is still an issue. #1562 was a PR with an attempted fix, not a dupe of this. 😄 

@robertjd had mentioned that there was another issue open for fixing this problem.

**Comment by jmelberg-okta** [comment] 2017-12-21 00:22
@natebarbettini-okta This problem is actually due to GA running on `support.okta.com`, not `developer.okta.com`. We cannot control this :bug:

**Comment by nbarbettini** [comment] 2017-12-21 00:39
How so? If I disable JavaScript on `developer.okta.com` and click the link, the page loads fine.

It looks like a script on `developer.okta.com` is adding the query param when the link is clicked:

![image](https://user-images.githubusercontent.com/7525482/34235125-5ba33f30-e5a4-11e7-9dd5-f9a4a8abf1d9.png)

Maybe I'm missing something here.

**Comment by jmelberg-okta** [comment] 2017-12-28 05:31
As discussed, this isn't an issue with `developer.okta.com`, but an issue with a script running on `support.okta.com`. Selecting certain `support.okta.com` links cause a redirect loop that eventually turn into a broken link (some require auth to proceed). Our link checking script picks up that this is a valid link, as the GA query params are not picked up.

The correct team has been notified of this bug.

**Comment by nbarbettini** [comment] 2018-01-09 20:29
Reopening since the link is still broken.

**Comment by jmelberg-okta** [comment] 2018-01-19 18:45
Resolved 1/19

**Closed by jmelberg-okta** 2018-01-19 18:45 UTC

**Comment by nbarbettini** [comment] 2018-01-19 23:02
Just tested and it works. Thanks @jmelberg-okta!
