### ISSUE TITLE
Longer {yourOktaDomain} links are half-blue

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta.github.io#1565] opened 2017-12-19 05:41 UTC
When a `{yourOktaDomain}` link is updated by the myOkta script, longer links are only half-affected: 

![half-hyperlink](https://user-images.githubusercontent.com/7525482/34142453-180cf7ca-e43c-11e7-9a57-f0ab0b426092.png)

Ideally any link that starts with `https://{yourOktaDomain}` would be transformed, regardless of how it ends.

**Comment by nbarbettini** [comment] 2017-12-19 20:55
I did a spot check and it looks like this is only happening on the blog (not docs or release notes). Some blog examples:

* https://developer.okta.com/blog/2017/11/20/build-an-iOS-app-with-secure-authentication-in-20-minutes
* https://developer.okta.com/blog/2017/10/19/use-openid-connect-to-build-a-simple-node-website

**Comment by mraible** [comment] 2017-12-19 20:57
Can we turn off linking in code blocks?

**Comment by jmelberg-okta** [comment] 2017-12-28 05:25
This is caused by a script injected into all blog pages. More specifically, it appears we use [VigLink](https://www.viglink.com/) to track click rates. Once the page loads, a script transforms the HTML of the page to highlight text starting with `http` or `https` into: `<div class="vglink">{text}</div>`.

My vote would be to remove the script as opposed to attempt to override it - but we need to ping Marketing first.

**Comment by jmelberg-okta** [comment] 2018-02-01 23:35
Closing this issue as it is out of our control. Please contact JLR for permission to remove.

**Closed by jmelberg-okta** 2018-02-01 23:35 UTC
Labels: bug

**Comment by aaronpk** [comment] 2018-12-05 23:30
Can we file an issue with VigLink? There is no situation in which they should be transforming the literal text `http://...` into a hyperlink when it's not already inside an `<a>` tag. Instead they should be traversing the DOM looking for `<a>` elements and replacing the `href` attribute with their own tracking thingy.

**Comment by mraible** [comment] 2018-12-06 22:34
I turned off both these settings for our Disqus instance.
